### ISSUE TITLE
Possibility to add some fixers / preset tags directly through the bridge

### ISSUE THREAD

**Issue by Soullivaneuh** [Soullivaneuh/php-cs-fixer-styleci-bridge#41]
To avoid `array_merge` usage like this: https://github.com/Soullivaneuh/php-cs-fixer-styleci-bridge/blob/f7d86d817843ada57948723e9a4cb14c32a3a490/README.md#psr-0-special-case

**Comment by GrahamCampbell** [comment]
psr0 IS supported by StyleCI?

**Comment by GrahamCampbell** [comment]
It's just not included in the presets anymore.

**Comment by Soullivaneuh** [comment]
> psr0 IS supported by StyleCI

Oh, I misunderstood that. I was thinking you completely removed it.

So if I do this:

```yaml
preset: none

enabled:
  - psr0
```

This will works?

**Comment by GrahamCampbell** [comment]
Yes.

**Comment by GrahamCampbell** [comment]
Or, just disabling psr4 on any of the other presets and enabling psr0.

**Comment by GrahamCampbell** [comment]
Like:

```yaml
preset: recommended

disabled:
  - psr4

enabled:
  - psr0
```

**Comment by GrahamCampbell** [comment]
Notice if you look on our fixer docs, we still list it as a fixer. :)

**Comment by GrahamCampbell** [comment]
And it's still in the `VALID` constant.

**Comment by Soullivaneuh** [comment]
Ok I see, thanks for the precision. :+1: 

I'll update the documentation ASAP.

**Comment by Soullivaneuh** [comment]
@GrahamCampbell Last question:

```yml
preset: symfony

disabled:
  - psr0
```

Will this work? Because PHP-CS-Fixer' Symfony preset enable psr0 AFAIK.
