### ISSUE TITLE
Manage non-array config values

### ISSUE THREAD

**Issue by Soullivaneuh** [Soullivaneuh/php-cs-fixer-styleci-bridge#43]
This config file sample will not pass actually:

```yml
preset: symfony

enabled: dummy_fixer

disabled: foo_bar_fixer

finder:
    exclude: res
```

@GrahamCampbell Could you please confirm that this is a valid config file?

Found here: https://github.com/puli/manager/blob/eddeb53ba314f866ac809d28544a1b35be4e77a9/.styleci.yml

**Comment by Soullivaneuh** [comment]
Doh! Thanks bro.

**Comment by GrahamCampbell** [comment]
Yes, it's a valid file, and it's working on styleci.io.

**Comment by Soullivaneuh** [comment]
@GrahamCampbell Does this apply to all finder options?

And what about `enabled` and `disabled`? Could this be scalar too? e.g.:

```yml
preset: symfony

enabled: dummy_fixer
disabled: foo_bar_fixer
```
