### ISSUE TITLE
PHP Fatal error:  Uncaught Error: Call to undefined method PhpCsFixer\Config::finder() in [...]vendor/sllh/php-cs-fixer-styleci-bridge/src/ConfigBridge.php:136

### ISSUE THREAD

**Issue by robfrawley** [Soullivaneuh/php-cs-fixer-styleci-bridge#75]
After my most recent `composer update` I am getting a fatal error when running `bin/php-cs-fixer` with the bridge.

```
bin/php-cs-fixer -vvv --dry-run fix
Fixer "short_array_syntax" does not exist, skipping.
Fixer "no_spaces_inside_offset" does not exist, skipping.
Fixer "no_tab_indentation" does not exist, skipping.
Fixer "unalign_double_arrow" does not exist, skipping.
Fixer "unalign_equals" does not exist, skipping.
Fixer "unix_line_endings" does not exist, skipping.
PHP Fatal error:  Uncaught Error: Call to undefined method PhpCsFixer\Config::finder() in /home/rmf/repos/composer/augustus-log-library/vendor/sllh/php-cs-fixer-styleci-bridge/src/ConfigBridge.php:136
Stack trace:
#0 /home/rmf/repos/composer/augustus-log-library/.php_cs.dist(27): SLLH\StyleCIBridge\ConfigBridge::create()
#1 /home/rmf/repos/composer/augustus-log-library/vendor/friendsofphp/php-cs-fixer/src/Console/ConfigurationResolver.php(179): include('/home/rmf/repos...')
#2 /home/rmf/repos/composer/augustus-log-library/vendor/friendsofphp/php-cs-fixer/src/Console/ConfigurationResolver.php(443): PhpCsFixer\Console\ConfigurationResolver->getConfig()
#3 /home/rmf/repos/composer/augustus-log-library/vendor/friendsofphp/php-cs-fixer/src/Console/ConfigurationResolver.php(262): PhpCsFixer\Console\ConfigurationResolver->getFormat()
#4 /home/rmf/repos/composer/augustus-log-library/vendor/friendsofphp/php-cs-fixer/src/Console/Command/FixCommand.php(321): PhpCsFixer\Console\ConfigurationResolver->getReporter()
#5 /home/rmf/repos/compo in /home/rmf/repos/composer/augustus-log-library/vendor/sllh/php-cs-fixer-styleci-bridge/src/ConfigBridge.php on line 136
```

With the following dependencies:

```json
"require-dev": {
  "friendsofphp/php-cs-fixer": "~2.0",
  "sllh/php-cs-fixer-styleci-bridge": "~2.1"
}
```

And the following `.php_cs.dist`

```php
<?php

use SLLH\StyleCIBridge\ConfigBridge;

require_once __DIR__.'/vendor/autoload.php';

$headerString = <<<EOF
[...] removed for brevity [...]
EOF;

$headerConfig = [ 'header_comment' => [ 'header' => $headerString ] ];

$config = ConfigBridge::create();
$config->setRules(array_merge($config->getRules(), $headerConfig));

return $config;
```

And the following `.styleci.yml`

```yml
---

preset: symfony

enabled:
  - combine_consecutive_unsets
  - linebreak_after_opening_tag
  - no_short_echo_tag
  - ordered_imports
  - phpdoc_order
  - php_unit_construct
  - php_unit_dedicate_assert
  - php_unit_strict
  - short_array_syntax

disabled:
  - simplified_null_return

finder :
  name    : [ "*.php", "*.twig" ]
  exclude : [ "vendor", "var" ]
  path    : [ "lib", "test" ]

...
```
