### ISSUE TITLE
Support for php-cs-fixer 2

### ISSUE THREAD

**Issue by core23** [soullivaneuh/php-cs-fixer-styleci-bridge#76]
Are there any plans for supporting the new major release?

Using this config produces some warnings
```yaml
# .styleci.yml
preset: symfony

enabled:
  - binary_operator_spaces
  - combine_consecutive_unsets
  - long_array_syntax
  - linebreak_after_opening_tag
  - no_php4_constructor
  - no_useless_else
  - ordered_class_elements
  - ordered_imports
  - php_unit_construct
  - php_unit_strict

finder:
  exclude:
    - 'Tests/Fixtures'
```

```
Fixer "align_double_arrow" does not exist, skipping.
Fixer "align_equals" does not exist, skipping.
Fixer "long_array_syntax" does not exist, skipping.
Fixer "unalign_double_arrow" does not exist, skipping.
Fixer "unalign_equals" does not exist, skipping.
Fixer "concat_without_spaces" does not exist, skipping.
Fixer "no_spaces_inside_offset" does not exist, skipping.
Fixer "no_tab_indentation" does not exist, skipping.
Fixer "phpdoc_type_to_var" does not exist, skipping.
Fixer "print_to_echo" does not exist, skipping.
Fixer "unix_line_endings" does not exist, skipping.
```

Are you planing to wrap the old name to the new syntax?
